### ISSUE TITLE
memory leak when connect interuped 

### ISSUE THREAD

**Issue by elderbig** [lodrem/etcd-rs#53]
at debug model,a lot of debug message print in log:
```
tonic-0.4.3/src/codec/decode.rs-> line:231]  decoder inner stream error: Status { code: Unknown, message: "h2 protocol error: broken pipe" } 
```
at the same time, memory using by tonic rise up and stand there,every time  interupt appeared,memory usage upgrade.

**Comment by elderbig** [comment]
[git@github.com:elderbig/etcd-rs-test.git](url)
this project show memory leak when etcd server interrupt

**Comment by elderbig** [comment]
function keep_alive will caught memroy leak when etcd server interrupt,like sample:

`client .lease().keep_alive(LeaseKeepAliveRequest::new(lease_id)).await.unwrap();`

**Comment by elderbig** [comment]
there another project 
[https://github.com/etcdv3/etcd-client](url)

there is no memory leak like this.

**Comment by luncj** [comment]
Thanks for the report. I have been busy with other work and will try to fix the problem in the next few days. And PRs are welcome if you have any ideas.

**Comment by lodrem** [comment]
I rewrite `lease` and `watch`. it should be fixed.
