### ISSUE TITLE
Tonic conflict

### ISSUE THREAD

**Issue by diggyk** [lodrem/etcd-rs#69]
Hello,

I'm using `tonic 0.7.1` for my project but `etcd-rs` is using `tonic 0.6` and this is causing a conflict.  Is there a way to address this?  It does look like there is some breaking changes, at least in module visibility in tonic.

**Comment by diggyk** [comment]
I've created a PR: https://github.com/lodrem/etcd-rs/pull/70

**Comment by lodrem** [comment]
fixed via https://crates.io/crates/etcd-rs/1.0.0-alpha.1
